### ISSUE TITLE
needle-2.2 not available in mvn repositories

### ISSUE THREAD

**Issue by jangalinski** [techatspree/needle#14]
I want to update my projects to needle-2.2, but it seems like it is not available in the central repository. I gave it some days now, but still the latest version is 2.1. Did you publish the release?

**Comment by hwilming** [comment]
Hi Jan,
please check your maven artifact coordinates. It should be available in maven central.
http://search.maven.org/#artifactdetails%7Cde.akquinet.jbosscc%7Cjbosscc-needle%7C2.2%7Cjar

Regards, Heinz

**Comment by jangalinski** [comment]
Thanks, Heinz. m2e had caching problems, tried mvn-console directly ... and of course you are right.
