### ISSUE TITLE
@PostConstruct not called on private/protected methods

### ISSUE THREAD

**Issue by jangalinski** [techatspree/needle#18]
Sorry for flip-flopping ,,,, due to a misleading, succeeding test-case I closed a similar issue earlier. Turns out this is a bug.  the PostConstructionProcessor currently only checks for public methods. The spec allows all modifiers and I have concrete case where the derived class wont work when the protected post-construct-method in super was not run.

I already have a fix (ReflectionUtil#getAllMethodsWithAnnotations) that I will commit soon.

**Comment by r0bb3n** [comment]
Is there any activity on this issue?

**Comment by jangalinski** [comment]
Fixed with commit 81b1b0da04d2a01007d36a5da4f253712744b7ea, see https://github.com/akquinet/needle/blob/master/src/test/java/de/akquinet/jbosscc/needle/postconstruct/PostConstructProcessorTest.java

**Comment by r0bb3n** [comment]
This issue should be associated to milestone 2.3 because it not included in needle 2.2 and it took me a while to find it out. :-( 
Are there plans for releasing version 2.3?

**Comment by jangalinski** [comment]
Sorry for the inconvenience. I got a bit quiet around needle, but I just recently talked to Heinz from akquinet and we pick up the pace now. 
The fix is in the master branch but I cannot tell any release dates.

**Comment by hwilming** [comment]
I plan to release the Version 2.3 in the next few weeks. The release will contain some bug fixes and the enhancements from Jan.
