### ISSUE TITLE
Feature: InjectionProviderInstancesSupplier

### ISSUE THREAD

**Issue by jangalinski** [techatspree/needle#21]
I extended needle to use it with activiti in memory tests. I need a lot of custom InjectionProviders which have quite a setup, so they and hardly be instantiated "on the fly" by using the Default Constructor.

What I need is an option between "hard configured injectionprovider-clasnames in properties" and "pass every single instance to the NeedleTestCase-Constructor when creating the rule".

I came up with the InjectProviderInstancesSupplier. Its an functional interface (see Java8, functional interface, Supplier), that provides a Set of InjectionProviders already instantiated. 

So instead of configuring or passing n Providers, I just configure one Supplier whose "get()" method gives you the actual InjectionProvider instances.

To make this work, we would have to create a common parent interface for the Supplier and the InjectionProvider so it is possible to mix Suppliers and Providers in the setup. 
The configuratin parts dealing with instantiating and merging all custom providers will have to recognize the two possible types and process them accordingly.

What do you think?

**Comment by hwilming** [comment]
+1
