### ISSUE TITLE
feature: provide InjectionProvider utils

### ISSUE THREAD

**Issue by jangalinski** [techatspree/needle#22]
Instead of implmenting the 3 injectionprovider methods every time, we could provide some default implementation (analog to the defaultmock). I have to candidates so far: 
- SingletonInstanceIP, just construct with an existing instance (bean, pojo, mock, ...) and whenever this instances type should be injected, the singleton instance is returned. 
- NamedInstanceProvider: bind an existing instance to a @Named value. Useful if you need more than one instance injected, for example named property Strings a.s.o.

I suggest to create an extra package for this kind of helper classes and add useful extensions every now and then.

**Comment by jangalinski** [comment]
+1 for 2.3, we already have these in needle-mockito and they are quiet useful.

**Comment by hwilming** [comment]
Hi Jan, would you like to contribute the code? Furthermore, we should have a similar InjectionProvider for CDI qualifier.

**Comment by jangalinski** [comment]
We now have a Util class "InjectionProviders" that offers 3 factory methods for creating providers for "instance", "namedInstance" and "qualifiedInstance".
