### ISSUE TITLE
add needle-h2-hibernate.cfg.xml

### ISSUE THREAD

**Issue by jangalinski** [techatspree/needle#23]
Although needle provides a H2-DB-Operation, it does not come with an h2 configuration. We should add one simple h2 default to src/main/resources

**Comment by jangalinski** [comment]
+1 for having this in 2.3. should be relatively easy to implement and would be of much help.

**Comment by hwilming** [comment]
It is not necessary to add an hibernate.cfg.xml for h2. I add an example for h2:
https://github.com/akquinet/needle/tree/master/src/examples/jpa-h2-example
