### ISSUE TITLE
Bug: No support for multiple "Instance<T>" injections

### ISSUE THREAD

**Issue by jangalinski** [techatspree/needle#25]
When my ObjectUnderTest uses more than one "Instance" injection:

@Inject
private Instance<Foo> foo;
@Inject
private Instance<Bar> bar;

and I use both of these instances in my Test class, I get a class cast exception (cannot cast Bar to Foo). Context seems to store just "Instance.class" and thus fails to use more than one ...

**Comment by jangalinski** [comment]
This really is a bummer. When using different scopes in CDI or lazy initialization, you easily end up with 2-3 or more "Instance<T>" injections in a bean. And you can not test those beans with needle because the injectionproviders cant handle generic types correctly. I even observed that I limit my production code to one "instance" so it remains testable, even if that validates layers or responsibilities.
I think this is critical and should be fixed. I will start with the test cases today. Could someone put this on the 2.3 agenda, please?

**Comment by hwilming** [comment]
I put on the roadmap of 2.3. Have you already started with the implementation? Can I assign the ticket to you?

**Comment by jangalinski** [comment]
Yes, assign it to me ... but I didnt start yet

**Comment by hwilming** [comment]
This is related to #11 and already done with the commit  3aa1783
