### ISSUE TITLE
Builders for NeedleRule

### ISSUE THREAD

**Issue by jangalinski** [techatspree/needle#26]
Needle is getting more and more configurable (caller instance in NeedleTestRule, properties File name, additional injectionProviders ...), the "create Rule by constructor" is becoming overloaded. I suggest providing NeedleRuleBuilders, so we can write:

@Rule
public final NeedleRule needle = NeedleRule.needleRule().properties("name.properties").injectionProvider(....).build();

I have done this for needle-mockito: https://github.com/holisticon/needle-mockito/blob/master/src/main/java/de/holisticon/toolbox/needle/NeedleTestRuleBuilder.java

**Comment by hwilming** [comment]
Hi Jan, would you like to contribute the code?

**Comment by jangalinski** [comment]
depends on #21

**Comment by jangalinski** [comment]
I think we can close this, right?

**Comment by jangalinski** [comment]
fixed with needle4j 2.3 https://github.com/needle4j/needle4j/blob/master/src/main/java/org/needle4j/junit/AbstractNeedleRuleBuilder.java
