### ISSUE TITLE
HSQLDeleteOperation is not working with Hibernate 4.3

### ISSUE THREAD

**Issue by OliverDamm** [techatspree/needle#29]
The HSQLDeleteOperation tries to open a JDBC connection using the properties from the EntityManagerFactory.getProperties() method. Hibernate 4.3 is masking out sensitive properties like the password property. So, the HSQLDeleteOperation tries to create a connection with a wrong password like '****'.

Setting the password directly in the needle.properties using 'jdbc.password' don't help.

Needle Version 2.2

Oliver

**Comment by jangalinski** [comment]
moved to https://github.com/needle4j/needle4j/issues/8
